name: Build C# Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'  # Schimbă cu versiunea ta de .NET

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet publish -c Release -r win-x64 --self-contained true -o build_output

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: Aplicatie
          path: build_output
